import { useEffect,useState } from "react";
import { apiRequest,authenticatedDownload } from "../lib/api";
import type { DrawDetails,LotteryDraw } from "../types";

const statusClass=(s:string)=>({Preparing:"bg-amber-100 text-amber-800",Ready:"bg-blue-100 text-blue-800","In Progress":"bg-purple-100 text-purple-800",Completed:"bg-green-100 text-green-800",Failed:"bg-red-100 text-red-800",Cancelled:"bg-slate-200 text-slate-800",Archived:"bg-slate-100 text-slate-600"}[s]||"bg-slate-100");
export function DrawHistory({buildingId,buildingName}:{buildingId:number;buildingName:string}){
 const[draws,setDraws]=useState<LotteryDraw[]>([]),[details,setDetails]=useState<DrawDetails|null>(null),[creating,setCreating]=useState(()=>new URLSearchParams(location.search).has("create")),[error,setError]=useState("");
 const[form,setForm]=useState({draw_name:"Remaining Residents Phase",phase_name:"",reason:"Additional allocation phase",planned_draw_date:"",notes:"",lottery_mode:"Full Allocation",waiting_list_enabled:false});
 const load=()=>apiRequest<LotteryDraw[]>(`/buildings/${buildingId}/draws`).then(setDraws);useEffect(()=>{setDraws([]);setDetails(null);void load()},[buildingId]);
 const setup=(id:number)=>{localStorage.setItem("ai_lottery_active_draw_cycle",String(id));history.pushState({},"","/draw-cycle-setup");dispatchEvent(new PopStateEvent("popstate"))};
 async function create(){try{const r=await apiRequest<{draw_id:number}>(`/buildings/${buildingId}/draw-cycles`,{method:"POST",body:JSON.stringify(form)});setCreating(false);await load();setup(r.draw_id)}catch(e){setError(e instanceof Error?e.message:"Creation failed")}}
 async function cancel(d:LotteryDraw){const reason=prompt("Enter cancellation reason");if(!reason)return;try{await apiRequest(`/buildings/${buildingId}/draw-cycles/${d.id}/cancel`,{method:"POST",body:JSON.stringify({reason,confirmed:true})});await load()}catch(e){setError(e instanceof Error?e.message:"Cancellation failed")}}
 const download=(d:LotteryDraw,kind:string)=>authenticatedDownload(`/buildings/${buildingId}/draws/${d.id}/${kind}`,`${d.draw_reference}-${kind}`);
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-3xl font-bold text-navy">Lottery Draw History — {buildingName}</h2><button className="rounded bg-blue-700 px-4 py-2 font-bold text-white" onClick={()=>setCreating(true)}>Create New Draw Cycle</button></div>{error&&<p className="rounded bg-red-50 p-3 font-bold text-red-700">{error}</p>}{draws.length===0?<p>No lottery draw history is available for this building.</p>:draws.map(d=><article className="rounded-lg border bg-white p-5" key={d.id}><div className="flex flex-wrap justify-between"><div><h3 className="text-xl font-bold">Draw {d.draw_number} — {d.draw_reference}</h3><p>{d.draw_name} {d.phase_name&&`· ${d.phase_name}`} · <b>{d.lottery_mode||"Full Allocation"}</b></p></div><span className={`h-fit rounded-full px-3 py-1 text-sm font-bold ${statusClass(d.status)}`}>{d.status}</span></div><p className="mt-2">Eligible {d.total_eligible??d.total_verified_residents} · Available rooms {d.total_available_rooms} · Winners {d.total_allocated} · Not Selected {d.total_not_selected??d.total_unallocated} · Waiting List {d.total_waiting_list??0} · {d.fairness_score}% fairness</p><div className="mt-3 flex flex-wrap gap-3">{d.status==="Preparing"&&<><button onClick={()=>setup(d.id)}>Continue Setup</button><button onClick={()=>void cancel(d)}>Cancel Cycle</button></>}{d.status==="Ready"&&<><button onClick={()=>setup(d.id)}>Review Eligibility</button><button onClick={()=>{localStorage.setItem("ai_lottery_active_draw_cycle",String(d.id));history.pushState({},"","/lottery");dispatchEvent(new PopStateEvent("popstate"))}}>Start Draw</button><button onClick={()=>void cancel(d)}>Cancel Cycle</button></>}{d.status==="Completed"&&<><button onClick={()=>void apiRequest<DrawDetails>(`/buildings/${buildingId}/draws/${d.id}`).then(setDetails)}>View Results</button><button onClick={()=>void download(d,"report.csv")}>Download CSV</button><button onClick={()=>void download(d,"report.pdf")}>Download PDF</button><button onClick={()=>void download(d,"certificate.pdf")}>Download Certificate</button></>}{d.status==="Cancelled"&&<span>Cancellation: {d.cancellation_reason}</span>}</div></article>)}
 {creating&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form className="w-full max-w-xl space-y-3 rounded bg-white p-6" onSubmit={e=>{e.preventDefault();void create()}}><h3 className="text-2xl font-bold">Create New Draw Cycle</h3><label className="block">Draw Name<input className="mt-1 w-full rounded border p-2" value={form.draw_name} onChange={e=>setForm({...form,draw_name:e.target.value})}/></label><label className="block">Lottery Mode<select aria-label="Lottery Mode" className="mt-1 w-full rounded border p-2" value={form.lottery_mode} onChange={e=>setForm({...form,lottery_mode:e.target.value,waiting_list_enabled:e.target.value==="Competitive Lottery"?form.waiting_list_enabled:false})}><option>Full Allocation</option><option>Competitive Lottery</option></select></label>{form.lottery_mode==="Competitive Lottery"&&<label className="flex items-center gap-2"><input aria-label="Enable Waiting List" type="checkbox" checked={form.waiting_list_enabled} onChange={e=>setForm({...form,waiting_list_enabled:e.target.checked})}/>Enable Waiting List</label>}<label className="block">Phase Name (optional)<input className="mt-1 w-full rounded border p-2" value={form.phase_name} onChange={e=>setForm({...form,phase_name:e.target.value})}/></label><label className="block">Reason for New Draw<textarea className="mt-1 w-full rounded border p-2" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><label className="block">Planned Draw Date<input type="date" className="mt-1 w-full rounded border p-2" value={form.planned_draw_date} onChange={e=>setForm({...form,planned_draw_date:e.target.value})}/></label><label className="block">Notes<textarea className="mt-1 w-full rounded border p-2" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="flex justify-end gap-3"><button type="button" onClick={()=>setCreating(false)}>Close</button><button className="rounded bg-blue-700 px-4 py-2 font-bold text-white">Create Cycle</button></div></form></div>}
 {details&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-8"><div className="mx-auto max-w-5xl rounded bg-white p-6"><button className="float-right" onClick={()=>setDetails(null)}>Close</button><h3 className="text-2xl font-bold">{details.draw.draw_reference} Results</h3><p className="mt-1">{details.draw.lottery_mode||"Full Allocation"} · Winners {details.draw.total_allocated} · Not Selected {details.draw.total_not_selected??details.draw.total_unallocated} · Waiting List {details.draw.total_waiting_list??0}</p>{["Winner","Allocated","Not Selected","Waiting List"].map(status=>{const rows=details.allocations.filter(a=>a.allocation_status===status);return rows.length?<section className="mt-4" key={status}><h4 className="font-bold">{status}s</h4>{rows.map(a=><p className="mt-2 rounded border p-3" key={a.id}><b>{a.resident_name_snapshot}</b>: {a.allocated_room_snapshot||"—"}{a.waiting_list_position?` · Position ${a.waiting_list_position}`:""}</p>)}</section>:null})}</div></div>}
 </div>
}
