import { useEffect,useState } from "react";
import { apiRequest } from "../lib/api";
import type { ResidentHistoryDetails,ResidentHistorySummary } from "../types";
export function ResidentHistory({buildingId,buildingName}:{buildingId:number;buildingName:string}){
 const [rows,setRows]=useState<ResidentHistorySummary[]>([]),[query,setQuery]=useState(""),[details,setDetails]=useState<ResidentHistoryDetails|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{setRows([]);setDetails(null);setLoading(true);apiRequest<ResidentHistorySummary[]>(`/buildings/${buildingId}/residents/history`).then(setRows).finally(()=>setLoading(false));},[buildingId]);
 const shown=rows.filter(r=>[r.full_name,r.old_room_number,r.aadhaar_masked,r.latest_allocated_room,r.latest_draw_reference,r.priority_category,r.verification_status].some(v=>String(v??"").toLowerCase().includes(query.toLowerCase())));
 async function open(id:number){setDetails(await apiRequest<ResidentHistoryDetails>(`/buildings/${buildingId}/residents/${id}/history`));}
 return <div className="space-y-5"><h2 className="text-3xl font-bold text-navy">Resident History — {buildingName}</h2><input aria-label="Search resident history" className="w-full rounded-lg border px-3 py-2" placeholder="Search name, old room, Aadhaar last four, allocated room or draw reference" value={query} onChange={e=>setQuery(e.target.value)}/>{loading?<p>Loading resident history…</p>:shown.length===0?<p>No resident history is available for this building.</p>:<div className="overflow-x-auto rounded-lg border bg-white"><table className="min-w-full text-sm"><thead><tr>{["Resident","Old Room","Priority","Verification","Latest Room","Latest Draw","Draws","Action"].map(x=><th className="p-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{shown.map(r=><tr className="border-t" key={r.id}><td className="p-3 font-bold">{r.full_name}<br/><span className="font-normal">{r.aadhaar_masked}</span></td><td>{r.old_room_number}</td><td>{r.priority_category}</td><td>{r.verification_status}</td><td>{r.latest_allocated_room??"Unallocated"}</td><td>{r.latest_draw_reference??"—"}</td><td>{r.draws_participated}</td><td><button className="font-bold text-blue-700" onClick={()=>void open(r.id)}>View History</button></td></tr>)}</tbody></table></div>}{details?<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-8"><div className="mx-auto max-w-4xl rounded-lg bg-white p-6"><button className="float-right" onClick={()=>setDetails(null)}>Close</button><h3 className="text-2xl font-bold">{details.resident.full_name}</h3><p>{details.building.building_name} · {details.building.society_name}</p><p className="mt-2">{details.resident.old_room_number} · {details.resident.priority_category} · {details.resident.verification_status}</p><h4 className="mt-5 text-xl font-bold">Chronological Timeline</h4>{details.events.map(e=><article className="mt-3 border-l-4 border-blue-600 pl-3" key={e.id}><b>{e.title}</b><p>{e.description}</p><small>{new Date(e.created_at).toLocaleString()} · {e.performed_by}</small></article>)}<h4 className="mt-5 text-xl font-bold">Draw Participation</h4>{details.draws.map(d=><article className="mt-3 rounded border p-3" key={d.id}><b>{d.draw_reference}</b><p>{d.old_room_snapshot} → {d.allocated_room_snapshot??"Unallocated"} · {d.allocation_status}</p><p>{d.ai_explanation}</p></article>)}</div></div>:null}</div>;
}
