import { expect,test,type APIRequestContext } from "@playwright/test";
import fs from "node:fs/promises";import path from "node:path";import {spawn,spawnSync} from "node:child_process";import http from "node:http";
const API="http://127.0.0.1:8010/api";
async function auth(r:APIRequestContext){const x=await r.post(`${API}/admin/login`,{data:{email:"admin@example.com",password:"admin123"}});return{Authorization:`Bearer ${(await x.json()).token}`}}
const building=(name:string,pin:string)=>({building_name:name,society_name:`${name} Society`,redevelopment_project_name:`${name} Project`,full_address:`1 ${name} Road`,city:"Mumbai",district:"Mumbai City",state:"Maharashtra",pin_code:pin,number_of_wings:1,description:"Cycle E2E"});
const resident=(name:string,id:string,room:string)=>({full_name:name,aadhaar_number:id,old_room_number:room,family_members:3,contact_number:"9456789012",priority_category:"General",building_wing:"A",document_name:null,consent:true});
const room=(n:string)=>({room_number:n,wing:"A",floor:1,size:"650 sq ft",status:"Available",suitable_for:"General"});
async function createCycle(r:APIRequestContext,h:Record<string,string>,bid:number,name:string){const x=await r.post(`${API}/buildings/${bid}/draw-cycles`,{headers:h,data:{draw_name:name,phase_name:name,reason:`Reason for ${name}`,planned_draw_date:null,notes:"E2E"}});expect(x.ok(),await x.text()).toBeTruthy();return await x.json()}
async function readyAndDraw(r:APIRequestContext,h:Record<string,string>,bid:number,did:number,rid:number,roomId:number){expect((await r.post(`${API}/buildings/${bid}/draw-cycles/${did}/residents`,{headers:h,data:{resident_id:rid,include:true,reason:"Selected"}})).ok()).toBeTruthy();expect((await r.post(`${API}/buildings/${bid}/draw-cycles/${did}/rooms`,{headers:h,data:{room_id:roomId,include:true,reason:"Selected"}})).ok()).toBeTruthy();expect((await r.post(`${API}/buildings/${bid}/draw-cycles/${did}/confirm`,{headers:h})).ok()).toBeTruthy();const x=await r.post(`${API}/buildings/${bid}/draw-cycles/${did}/draw`,{headers:h});expect(x.ok(),await x.text()).toBeTruthy();return await x.json()}
function ready(url:string){return new Promise<boolean>(resolve=>{const q=http.get(url,res=>{res.resume();resolve(res.statusCode===200)});q.on("error",()=>resolve(false));q.setTimeout(500,()=>{q.destroy();resolve(false)})})}

test("building supports independent completed, cancelled and restart-safe draw cycles",async({request,page})=>{
 const h=await auth(request);const a=(await(await request.post(`${API}/buildings`,{headers:h,data:building("Cycle Building A","402001")})).json()).building;const b=(await(await request.post(`${API}/buildings`,{headers:h,data:building("Cycle Building B","402002")})).json()).building;
 const r1=(await(await request.post(`${API}/buildings/${a.id}/residents`,{headers:h,data:resident("Cycle Resident One","877700000001","CA-OLD-1")})).json()).resident;const r2=(await(await request.post(`${API}/buildings/${a.id}/residents`,{headers:h,data:resident("Cycle Resident Two","877700000002","CA-OLD-2")})).json()).resident;
 await request.post(`${API}/buildings/${a.id}/residents/${r1.id}/verify`,{headers:h});await request.post(`${API}/buildings/${a.id}/residents/${r2.id}/verify`,{headers:h});const room1=await(await request.post(`${API}/buildings/${a.id}/rooms`,{headers:h,data:room("CA-101")})).json();const room2=await(await request.post(`${API}/buildings/${a.id}/rooms`,{headers:h,data:room("CA-102")})).json();
 const d1=await createCycle(request,h,a.id,"Main Allocation");const draw1=await readyAndDraw(request,h,a.id,d1.draw_id,r1.id,room1.id);const before=await(await request.get(`${API}/buildings/${a.id}/draws/${d1.draw_id}`,{headers:h})).json();expect(before.draw.status).toBe("Completed");
 expect((await request.put(`${API}/buildings/${a.id}/draw-cycles/${d1.draw_id}`,{headers:h,data:{draw_name:"Changed",reason:"No",phase_name:null,planned_draw_date:null,notes:null}})).status()).toBe(409);
 const d2=await createCycle(request,h,a.id,"Remaining Residents");const eligibility=await(await request.get(`${API}/buildings/${a.id}/draw-cycles/${d2.draw_id}/eligibility`,{headers:h})).json();expect(eligibility.residents.find((x:{resident_id:number})=>x.resident_id===r1.id).eligibility_status).toBe("Already Allocated");expect(eligibility.residents.find((x:{resident_id:number})=>x.resident_id===r2.id).eligibility_status).toBe("Eligible");expect(eligibility.rooms.find((x:{room_id:number})=>x.room_id===room1.id).eligibility_status).toBe("Already Allocated");
 expect((await request.post(`${API}/buildings/${a.id}/draw-cycles/${d2.draw_id}/rooms`,{headers:h,data:{room_id:room1.id,include:true,reason:"reuse"}})).status()).toBe(409);expect((await request.post(`${API}/buildings/${b.id}/draw-cycles/${d2.draw_id}/residents`,{headers:h,data:{resident_id:r2.id,include:true}})).status()).toBe(404);
 const draw2=await readyAndDraw(request,h,a.id,d2.draw_id,r2.id,room2.id);expect(draw2.lottery_seed).not.toBe(draw1.lottery_seed);const after=await(await request.get(`${API}/buildings/${a.id}/draws/${d1.draw_id}`,{headers:h})).json();expect(after).toEqual(before);expect((await(await request.get(`${API}/buildings/${a.id}/draws/${d2.draw_id}`,{headers:h})).json()).allocations).toHaveLength(1);
 const history=await(await request.get(`${API}/buildings/${a.id}/residents/${r2.id}/history`,{headers:h})).json();expect(history.draws.map((x:{draw_reference:string})=>x.draw_reference)).toEqual(expect.arrayContaining([d1.draw_reference,d2.draw_reference]));
 const csv1=await(await request.get(`${API}/buildings/${a.id}/draws/${d1.draw_id}/report.csv`,{headers:h})).text();const csv2=await(await request.get(`${API}/buildings/${a.id}/draws/${d2.draw_id}/report.csv`,{headers:h})).text();expect(csv1).toContain("Cycle Resident One");expect(csv1).not.toContain("Cycle Resident Two");expect(csv2).toContain("Cycle Resident Two");
 const d3=await createCycle(request,h,a.id,"Cancelled Phase");expect((await request.post(`${API}/buildings/${a.id}/draw-cycles/${d3.draw_id}/cancel`,{headers:h,data:{reason:"No longer required",confirmed:true}})).ok()).toBeTruthy();expect((await request.post(`${API}/buildings/${a.id}/draw-cycles/${d3.draw_id}/draw`,{headers:h})).status()).toBe(409);const cycles=await(await request.get(`${API}/buildings/${a.id}/draws`,{headers:h})).json();expect(cycles.find((x:{id:number})=>x.id===d3.draw_id).status).toBe("Cancelled");expect(await(await request.get(`${API}/buildings/${b.id}/draws`,{headers:h})).json()).toEqual([]);
 await page.goto("/admin-login");await page.getByLabel("Admin Email").fill("admin@example.com");await page.getByLabel("Password").fill("admin123");await page.getByRole("button",{name:"Login as Admin"}).click();await page.getByLabel("Current Building:").selectOption(String(a.id));await page.getByRole("button",{name:"Draw History",exact:true}).click();await expect(page.getByText(d2.draw_reference)).toBeVisible();
 const pidFile=path.resolve("test-results/servers.json");const pids=JSON.parse(await fs.readFile(pidFile,"utf8")) as number[];if(process.platform==="win32")spawnSync("taskkill",["/pid",String(pids[0]),"/T","/F"],{stdio:"ignore"});else process.kill(-pids[0],"SIGTERM");const database=path.resolve("test-results/ai-lottery-e2e.sqlite");const backend=spawn("python",["-m","uvicorn","backend.app.main:app","--host","127.0.0.1","--port","8010"],{cwd:path.resolve(".."),detached:true,env:{...process.env,AI_LOTTERY_DB:database},stdio:"ignore"});backend.unref();pids[0]=backend.pid!;await fs.writeFile(pidFile,JSON.stringify(pids));for(let i=0;i<30&&!await ready(`${API}/health`);i++)await new Promise(x=>setTimeout(x,250));const h2=await auth(request);expect(await(await request.get(`${API}/buildings/${a.id}/draws`,{headers:h2})).json()).toHaveLength(3);
});
